version: '3.1'

services:
  postgres:
    image: postgres:14
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${POSTGRES_PORT}:5432

  mongo:
    image: mongo:5.0
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./database/mongo/init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro